### ISSUE TITLE
mysql-shell-innotop doesn't work with MySQL Shell 8.0.18

### ISSUE THREAD

**Issue by yoku0825** [lefred/mysql-shell-innotop#4]
Because MySQL Shell 8.0.18 is using Python 3.x

[MySQL Shell 8\.0\.18 – What’s New? \| MySQL Server Blog](https://mysqlserverteam.com/mysql-shell-8-0-18-whats-new/)

```
 MySQL  localhost  Py > import sys
 MySQL  localhost  Py > sys.path.append('/home/yoku0825/mysql-shell-innotop')
 MySQL  localhost  Py > import innotop
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoku0825/.mysqlsh/mysql-shell-innotop/innotop.py", line 8, in <module>
    from modules import *
  File "/home/yoku0825/.mysqlsh/mysql-shell-innotop/modules/common.py", line 1, in <module>
    import __builtin__
ModuleNotFoundError: No module named '__builtin__'
```

**Comment by lefred** [comment]
It's fixed and pushed
